version: '3'

dotenv: ['.env']

tasks:
  build:
    desc: Build the binary to .bin/
    cmds:
      - mkdir -p .bin
      - go build -o .bin/telegram-nats-bridge .

  run:
    desc: Run for development (requires config.yaml)
    cmds:
      - go run . run --config config.yaml

  check-bot:
    desc: Check bot and print updates as JSON (requires config.yaml)
    cmds:
      - go run . check bot --config config.yaml

  test:
    desc: Run tests
    cmds:
      - go test ./...

  nats-sub:
    desc: Subscribe to NATS subject (requires running nats container)
    cmds:
      - docker run --rm -it --network host natsio/nats-box nats sub telegram.updates

  nats-up:
    desc: Start NATS server with Docker Compose
    cmds:
      - docker compose -f docker-compose.example.yaml up -d

  nats-down:
    desc: Stop NATS server
    cmds:
      - docker compose -f docker-compose.example.yaml down
